# Generated by Django 2.2.5 on 2019-09-07 16:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AcceptOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Your phone number is error!', regex='^\\+?1?\\d{9,15}$')])),
                ('car_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Your car number is error!', regex='^\\d{2}\\w{1}\\d{3}\\w{2}$')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderStatus')),
            ],
        ),
    ]
